### PR TITLE
Exercise Submission

### PR DESCRIPTION
**Pull request by walt-1**

### CODE REVIEW

**Comment by C-Stein** [comment]
Nice work- you've got all the tricky things working great! A couple of suggestions for improvement: 1) Go ahead and add jQuery, even if you're not going to use i since bootstrap requires it. 2) 9. in the directions say "Also, on click of the car element, clear the value of the text input in the navbar...", which I would interpret as starting with an empty text field instead of populating the text field with the current description. 3) Your style function accepts a "color" argument, but then doesn't do anything with it.

**Comment by walt-1** [comment]
Hey Caitlin, I changed my code based on your guidance and suggestions. Let me know if it is ok to merge!

**Comment by dmserrano** [comment]
Almost there. It looks like when I select a div now, all of the text in the div is erased. It could possibly be a css thing.

The style function accepts the color argument, and adds the class to the div, but it does not actually change the background. Technically, you are using it now, but adding a class to the selected div should change styling / background.

**Comment by dmserrano** [comment]
You are good to merge 👍

**Pull request merged**
